name: post-ai

services:
  post-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: post-ai:latest
    container_name: post-ai
    env_file: .env
    environment:
      GEMINI_LLM_MODEL: ${GEMINI_LLM_MODEL:-gemini/gemini-1.5-flash}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GROQ_MODEL_NAME: ${GROQ_MODEL_NAME:-groq/deepseek-r1-distill-llama-70b}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SERPER_API_KEY: ${SERPER_API_KEY}
      AGENTOPS_API_KEY: ${AGENTOPS_API_KEY}
    ports:
      - 10000:10000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:10000/_stcore/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
