research:
  description: >
    1. Priorize as últimas tendências, os principais autores e as notícias mais relevantes sobre {tema}.
    2. Identifique o público-alvo, considerando seus interessses e pontos de dor.
    3. Inclua palavras-chaves de SEO e dados ou fontes relevantes.
    4. Faça as pesquisas no idioma {idioma}.
  expected_output: >
    Um plano de tendências sobre {tema}, com as palavras mais relevantes de SEO e as últimas notícias.
    Traga embasamento no conteúdo com base na pesquisa realizada.
    Faça o retorno do conteúdo utilizando o idioma {idioma}.
  agent: researcher

write:
  description: >
    1. Use os dados coletados de conteúdo para criar um post de LinkedIn atraente sobre {tema}.
    2. Incorpore palavras-chave de SEO de forma natural.
    3. Organize o texto de forma BEM estruturada, definindo o título e subtítulos que estejam alinhados com o tópico abordado.
    4. Explore ótimas estratégias/explicações de comunicação que estejam alinhados com o tom, aspectos e tema de artigo em questão.
    5. Divida em parágrafos, tópicos, bullet points, tudo para melhor compreensão dos leitores.
    6. Certifique-se de que o post esteja estruturado de forma cativante, com uma conclusão que faça o leitor refletir.
  expected_output: >
    Um texto de LinkedIn sobre {tema}.
    Faça o retorno do conteúdo utilizando o idioma {idioma}.
  agent: writer

edit:
  description: >
    1. Revisar a postagem do LinkedIn em questão quanto a erros gramaticais.
    2. Verifique também o alinhamento com a voz pessoal de uma pessoa mais {tom}.
    3. Defina o título em Markdown como: '# (título)'. Que esteja em conformidade com o tópico.
    4. Defina os subtópicos da postagem, tendo relação com tom de voz e conteúdo gerado.
    5. Use explicações argumentativas por parágrafo por extenso.
    6. Use com moderação bullet points, estruture e explique bem o subtópico em questão.
    7. Formate as palavras-chaves relevantes no final da postagem na conclusão.
    8. Cada palavras-chave (keyword) com hashtag (#keyword) e separadas por um espaço.
  expected_output: >
    Um texto de LinkedIn pronto para publicação, seguindo o tom de voz esperado.
    Uma postagem de LinkedIn bem formatada e que atraía boas impressões.
    O retorno do conteúdo utilizando o idioma {idioma}.
  agent: editor
